kisaltmalar = {
    "AA":  "Anadolu Ajansı", 
    "AAET":  "Avrupa Atom Enerjisi Topluluğu",
    "AB": "Avrupa Birliği",  
    "ABB": "Avrupa Birliği Bankası",
    "ABGS": "Avrupa Birliği Genel Sekreterliği",
    "ABKF": "Avrupa Bölgesel Kalkınma Fonu",
    "ABÖ": "Afrika Birliği Örgütü",
    "ACÜ": "Acıbadem Üniversitesi", 
    "AÇSAP": "Ana Çocuk Sağlığı ve Aile Planlaması Genel Müdürlüğü", 
    "ADKF": "Abu Dabi Kalkınma Fonu",  
    "ADSL": "Asimetrik sayısal abone hattı (Asymmetric Digital Subscriber Line)", 
    "ADÜ": "Adnan Menderes Üniversitesi", 
    "ADYÜ": "Adıyaman Üniversitesi",
    "AEGM": "Kültür ve Turizm Bakanlığı Araştırma ve Eğitim Genel Müdürlüğü", 
    "AEİBÖ": "Avrupa Ekonomik İş Birliği Örgütü",  
    "AET": "Avrupa Ekonomik Topluluğu",  
    "AEÜ": "Ahi Evran Üniversitesi",
    "AFAD": "Afet ve Acil Durum Yönetimi Başkanlığı", 
    "AFFB": "Avrupa Futbol Federasyonları Birliği",  
    "AFİF": "Akaryakıt Fiyat İstikrar Fonu",
    "AGİK": "Avrupa Güvenlik ve İş Birliği Konferansı", 
    "AGİT": "Avrupa Güvenlik ve İş Birliği Teşkilatı", 
    "AGM": "Ağaçlandırma ve Erozyon Kontrolü Genel Müdürlüğü", 
    "AİBÖ": "Avrupa İş Birliği Örgütü",  
    "AİBÜ": "Abant İzzet Baysal Üniversitesi", 
    "AİÇÜ": "Ağrı İbrahim Çeçen Üniversitesi",
    "AIDS": "Edinilmiş bağışıklık yetersizliği belirtisi",  
    "AİHAD": "Avrupa İnsan Hakları Adalet Divanı",
    "AİHM": "Avrupa İnsan Hakları Mahkemesi",
    "AİHS": "Avrupa İnsan Hakları Sözleşmesi", 
    "AİK": "Afrika İktisat Komisyonu", 
    "AİKB": "Avrupa İmar ve Kalkınma Bankası", 
    "AİPB": "Avrupa İktisadi ve Parasal Birliği",
    "AK": "Avrupa Konseyi", 
    "AKB": "Afrika Kalkınma Bankası", 
    "AKBB": "Afrika Kalkınma Bankaları Birliği", 
    "AKBİL": "Akıllı bilet",
    "AKÇT": "Avrupa Kömür ve Çelik Topluluğu",  
    "AKD": "Akdeniz Üniversitesi" ,
    "AKDTYK": "Atatürk Kültür, Dil ve Tarih Yüksek Kurumu", 
    "AKM": "Atatürk Kültür Merkezi", 
    "AKPM": "Avrupa Konseyi Parlamenterler Meclisi",
    "AKUT": "Arama Kurtarma Teşkilatı",
    "AKÜ": "Afyon Kocatepe Üniversitesi",
    "Alb.": "Albay",
    "ALES": "Akademik Personel ve Lisanüstü Eğitimi Giriş Sınavı", 
    "Alm.":  "Almanca", 
    "AMB": "Amerika Merkez Bankası", 
    "AMK": "Amerikan Merkez Komutanlığı", 
    "ANAM": "Avrupa Nükleer Araştırma Merkezi",  
    "anat.": "Anatomi",
    "ANAÜ": "Anadolu Üniversitesi", 
    "ANT": "Akaryakıt İkmal ve Nato Pol Tesisleri İşletme Başkanlığı",
    "ant.": "Antropoloji", 
    "AO": "Anonim ortaklık", 
    "AOÇ": "Atatürk Orman Çiftliği", 
    "AÖB": "Avrupa Ödemeler Birliği", 
    "AÖF": "Açıköğretim Fakültesi", 
    "AP": "ABD Haber Ajansı", 
    "APA": "Avrupa Para Anlaşması", 
    "APB": "Avrupa Para Birliği", 
    "APE": "Avrupa Para Enstitüsü", 
    "APF": "Arap Para Fonu", 
    "APİİB": "Asya Pasif ik İktisadi İş Birliği",  
    "APÖ": "Avrupa Parlamenterler Örgütü",  
    "APS": "Acele Posta Servisi", 
    "Apt.": "Apartman", 
    "Ar.": "Arapça", 
    "AREL": "İstanbul Arel Üniversitesi", 
    "AR-GE": "Araştırma geliştirme", 
    "ark.": "Arkeoloji", 
    "Arş. Gör.": "Araştırma Görevlisi", 
    "As.": "Asker",
    "As. İz.": "Askerî İnzibat", 
    "ASAL": "Asker Alma Dairesi Başkanlığı", 
    "Asb.": "Astsubay", 
    "ASELSAN": "Askerî Elektronik Sanayi", 
    "ASF": "Avrupa Sosyal Fonu",
    "ASİGM": "Adli Sicil ve İstatistik Genel Müdürlüğü", 
    "ASK": "Avrupa Standartlar Komitesi", 
    "ASKİ": "Ankara Su ve Kanalizasyon İdaresi", 
    "ASO": "Ankara Sanayi Odası", 
    "AST": "Ankara Sanat Tiyatrosu", 
    "ASTB": "Amerika Serbest Ticaret Bölgesi",
    "astr.": "Astronomi", 
    "astrol.": "Astroloji", 
    "ASÜ": "Aksaray Üniversitesi", 
    "AŞ": "Anonim şirket", 
    "AŞTİ": "Ankara Şehirler Arası Terminal İşletmesi", 
    "AT": "Avrupa Topluluğu",
    "ATAD": "Avrupa Toplulukları Adalet Divanı", 
    "ATAM": "Atatürk Araştırma Merkezi", 
    "ATATÜRK ÜNİ": "Atatürk Üniversitesi",
    "ATB": "Asya Takas Birliği", 
    "Atğm.": "Asteğmen", 
    "ATK": "Adli Tıp Kurumu", 
    "atm.": "Atmosfer", 
    "ATO": "Ankara Ticaret Odası", 
    "ATÜ": "Atılım Üniversitesi", 
    "ATYGF": "Avrupa Tarımsal Yönlendirme ve Garanti Fonu",  
    "AUA": "Avrupa Uzay Ajansı", 
    "AÜ": "Ankara Üniversitesi",
    "Av.": "Avukat", 
    "AVM": "Alışveriş merkezi", 
    "AYB": "Avrupa Yayın Birliği", 
    "AYİM": "Askerî Yüksek İdare Mahkemesi", 
    "AYM": "Anayasa Mahkemesi", 
    "BADET": "Batı Afrika Devletleri Ekonomik Topluluğu", 
    "BAE": "Birleşik Arap Emirlikleri", 
    "bağ.": "Bağlaç", 
    "BAĞ-KUR": "Esnaf ve Sanatkârlar ve Diğer Bağımsız Çalışanlar Sosyal Sigortalar Kurumu", 
    "BAKB": "Batı Afrika Kalkınma Bankası",
    "BASAGM": "Başbakanlık Aile ve Sosyal Araştırmalar Genel Müdürlüğü", 
    "BATO": "Batı Afrika Takas Odası", 
    "BAU": "Bahçeşehir Üniversitesi", 
    "BAÜN": "Balıkesir Üniversitesi", 
    "BAY ÜNİ": "Bayburt Üniversitesi", 
    "BBC": "İngiliz Radyo Televizyon Kurumu",  
    "BCG": "Verem aşısı", 
    "Bçvş.": "Başçavuş", 
    "BD": "Bilim dalı", 
    "BDDK": "Bankacılık Düzenleme ve Denetleme Kurulu", 
    "BDT": "Bağımsız Devletler Topluluğu",  
    "BE": "Büyükelçi", 
    "BEÜ": "Bitlis Eren Üniversitesi", 
    "BİB": "Bayındırlık ve İskân Bakanlığı", 
    "BİK": "Basın İlan Kurumu",  
    "bit. b.": "Bitki bilimi", 
    "biy.": "Biyoloji", 
    "bk.": "Bakınız", 
    "bl.": "Bilişim", 
    "Bl.": "Bölük", 
    "BM": "Birleşmiş Milletler", 
    "BMAEK": "Birleşmiş Milletler Avrupa Ekonomik Komisyonu", 
    "BMÇYT": "Birleşmiş Milletler Çocuklara Yardım Teşkilatı", 
    "BMEBKT": "Birleşmiş Milletler Eğitim, Bilim ve Kültür Teşkilatı", 
    "BMSKÖ": "Birleşmiş Milletler Sınai Kalkınma Örgütü", 
    "BMT": "Birleşmiş Milletler Teşkilatı",  
    "BMTKK": "Birleşmiş Milletler Ticaret ve Kalkınma Konferansı",
    "BMYRİ": "Birleşmiş Milletler Yardım ve Rehabilitasyon İdaresi",  
    "Bn.": "Bayan", 
    "Bnb.": "Binbaşı", 
    "BOREN": "Ulusal Bor Araştırma Enstitüsü ",
    "BOTAŞ": "Boru Hatları ile Petrol Taşıma Anonim Şirketi", 
    "Böl.": "Bölüm", 
    "BRT": "Bartın Üniversitesi", 
    "bs.": "Baskı",
    "Bşk.": "Başkan", 
    "BTF": "Başbakanlık Tanıtma Fonu Kurulu", 
    "BTK": "Bilgi Teknolojileri ve İletişim Kurumu", 
    "BTÜ": "Bursa Teknik Üniversitesi",
    "Bul.": "Bulvar", 
    "Bulg.": "Bulgarca", 
    "BÜ": "Boğaziçi Üniversitesi",
    "BÜMKO": "Bütçe ve Mali Kontrol Genel Müdürlüğü",
    "BVÜ": "Bezmiâlem Vakıf Üniversitesi", 
    "BYEGM": "Basın-Yayın ve Enformasyon Genel Müdürlüğü", 
    "Cad.": "Cadde",
    "CBÜ": "Celâl Bayar Üniversitesi", 
    "CC": "Konsolosluk birimi",  
    "CGS": "Uluslararası fizik birimleri sistemi", 
    "CIF": "Maliyet-sigorta-navlun",
    "CİGM": "Ceza İşleri Genel Müdürlüğü", 
    "CIP": "Taşıma ve sigorta bedeli ödenmiş olarak teslim",
    "cm": "Santimetre", 
    "CMK": "Ceza Muhakemesi Kanunu", 
    "CMUK": "Ceza Muhakemeleri Usulü Kanunu", 
    "coğ.": "Coğrafya", 
    "cos": "Kosinüs",
    "CSO": "Cumhurbaşkanlığı Senfoni Orkestrası", 
    "CTE": "Ceza ve Tevkifevleri Genel Müdürlüğü", 
    "Cum. Bşk.": "Cumhurbaşkanı", 
    "CÜ": "Cumhuriyet Üniversitesi", 
    "ÇAĞ ÜNİ": "Çağ Üniversitesi", 
    "ÇASGEM": "Çalışma ve Sosyal Güvenlik Eğitim ve Araştırma Merkezi", 
    "ÇAYKUR": "Çay İşletmeleri Genel Müdürlüğü", 
    "ÇED": "Çevresel Etki Değerlendirmesi ve Planlama Genel Müdürlüğü",
    "çev.": "Çeviren", 
    "ÇGM": "Çalışma ve Sosyal Güvenlik Bakanlığı Çalışma Genel Müdürlüğü", 
    "ÇNÜ": "Çankırı Karatekin Üniversitesi", 
    "ÇOMÜ": "Çanakkale Onsekiz Mart Üniversitesi", 
    "ÇS": "Çimento Sanayisi", 
    "ÇSGB": "Çalışma ve Sosyal Güvenlik Bakanlığı", 
    "ÇUKOBİRLİK": "Çukurova Pamuk Tarım Satış Kooperatifleri Birliği", 
    "ÇÜ": "Çankaya Üniversitesi", 
    "Çvş.": "Çavuş", 
    "ÇYGM": "Çevre Yönetimi Genel Müdürlüğü", 
    "DAGM": "Devlet Arşivleri Genel Müdürlüğü", 
    "DAKB": "Doğu Afrika Kalkınma Bankası",
    "dal": "Dekalitre", 
    "dam": "Dekametre", 
    "DAP": "Doğu Anadolu Projesi", 
    "DAT": "Doğu Afrika Topluluğu", 
    "DB": "Dünya Bankası", 
    "db.": "Dil bilgisi", 
    "DBAFİT": "Dünya Bankalar Arası Finansal İletişim Topluluğu", 
    "DDB": "Dernekler Dairesi Başkanlığı",
    "DDY": "Devlet Deniz Yolları", 
    "DESİYAB": "Devlet Sanayi ve İşçi Yatırım Bankası", 
    "DEÜ": "Dokuz Eylül Üniversitesi",
    "DFİF": "Destekleme ve Fiyat İstikrar Fonu", 
    "DFMHÖ": "Dünya Fikrî Mülkiyet Hakları Örgütü",
    "dg": "Desigram",
    "DGK": "Dünya Gıda Konseyi", 
    "DGM": "Devlet Güvenlik Mahkemesi", 
    "DGÖ": "Dünya Gümrük Örgütü", 
    "DGS": "Dikey Geçiş Sınavı", 
    "DHMİ": "Devlet Hava Meydanları İşletmesi",
    "DİB": "Diyanet İşleri Başkanlığı", 
    "DİE": "Devlet İstatistik Enstitüsü", 
    "dil b.": "Dil bilimi", 
    "DİYİH": "Çalışma ve Sosyal Güvenlik Bakanlığı Dış İlişkiler ve Yurt Dışı İşçi Hizmetleri Genel Müdürlüğü", 
    "dk.": "Dakika", 
    "DKK": "Deniz Kuvvetleri Komutanlığı",
    "DKMP": "Doğa Koruma ve Millî Parklar Genel Müdürlüğü", 
    "dl": "Desilitre", 
    "DLH": "Demiryollar Limanlar ve Hava Meydanları İnşaatı Genel Müdürlüğü", 
    "dm": "Desimetre", 
    "DMİ": "Devlet Meteoroloji İşleri Genel Müdürlüğü", 
    "DMO": "Devlet Malzeme Ofisi", 
    "DNA": "Deoksirübo nükleik asit", 
    "DOBGM": "Devlet Opera ve Balesi Genel Müdürlüğü", 
    "Doç.": "Doçent", 
    "doğ.": "Doğum tarihi", 
    "DOÜ": "Doğuş Üniversitesi",
    "DÖGM": "Din Öğretimi Genel Müdürlüğü", 
    "DÖSİM": "Kültür ve Turizm Bakanlığı Döner Sermaye İşletmesi Merkez Müdürlüğü",
    "DPB": "Devlet Planlama Başkanlığı",
    "DPT": "Devlet Planlama Teşkilatı Müsteşarlığı", 
    "DPÜ": "Dumlupınar Üniversitesi", 
    "Dr.": "Doktor", 
    "drl.": "Derleyen", 
    "DSİ": "Devlet Su İşleri Genel Müdürlüğü", 
    "DSO": "Devlet Sanayi Ofisi", 
    "DSÖ": "Dünya Sağlık Örgütü", 
    "DT": "Devlet Tiyatroları Genel Müdürlüğü", 
    "DTCF": "Dil ve Tarih-Coğrafya Fakültesi", 
    "DTM": "Dış Ticaret Müsteşarlığı",
    "DTÖ": "Dünya Ticaret Örgütü", 
    "DÜ": "Dicle Üniversitesi", 
    "Dz. Kuv. K.": "Deniz Kuvvetleri Komutanı", 
    "Dz. Kuv.": "Deniz Kuvvetleri", 
    "dzl.": "Düzenleyen", 
    "EAT": "Eski Anadolu Türkçesi", 
    "EBK": "Et ve Balık Kurumu Genel Müdürlüğü", 
    "Ecz.": "Eczacı", 
    "ed.": "Editör", 
    "EEG": "Beyin akım grafiği", 
    "EFT": "Bankalar arası para aktarımı",
    "EGM": "Emniyet Genel Müdürlüğü", 
    "EGO": "Ankara Belediyesi Elektrik, Gaz, Otobüs İşletmeleri", 
    "EĞİTEK": "Eğitim Teknolojileri Genel Müdürlüğü", 
    "EİBKT": "Ekonomik İş Birliği ve Kalkınma Teşkilatı", 
    "EİBÖ": "Ekonomik İş Birliği Örgütü",
    "EİEİ": "Elektrik İşleri Etüt İdaresi Genel Müdürlüğü", 
    "EKG": "Kalp akım grafiği", 
    "ekon.": "Ekonomi", 
    "EMG": "Kasakım grafiği",
    "EMK": "Elektromotor kuvvet", 
    "Ens.": "Enstitü", 
    "EPDK": "Enerji Piyasası Düzenleme Kurulu", 
    "ERDEMİR": "Ereğli Demir Çelik Fabrikaları", 
    "Erm.": "Ermenice", 
    "ERÜ": "Erciyes Üniversitesi", 
    "ESGM": "Esnaf ve Sanatkârlar Genel Müdürlüğü", 
    "ESHOT": "İzmir Belediyesi Elektrik, Su, Hava Gazı, Otobüs, Tramvay İşletmeleri", 
    "ESOGÜ": "Eskişehir Osmangazi Üniversitesi", 
    "ET": "Eski Türkçe",
    "ETKB": "Enerji ve Tabii Kaynaklar Bakanlığı", 
    "ETOGM": "Erkek Teknik Öğretim Genel Müdürlüğü",
    "EÜ": "Ege Üniversitesi", 
    "EÜAŞ": "Elektrik Üretim Anonim Şirketi", 
    "EXİMBANK": "Türkiye İhracat ve Kredi Bankası", 
    "FAB": "Federal Araştırma Bürosu", 
    "Fak.": "Fakülte", 
    "Fak-Fuk": "Fon Sosyal Yardımlaşma ve Dayanışmayı Teşvik Fonu", 
    "Far.": "Farsça", 
    "FBA": "Fransız Basın Ajansı",  
    "fel.": "Felsefe", 
    "fil.": "Filoloji", 
    "FIR": "Uçuş hattı düzenlemesi",
    "FİSKOBİRLİK": "Fındık Tarım Satış Kooperatifleri Birliği", 
    "fiz.": "Fizik", 
    "fizy.": "Fizyoloji", 
    "FKB": "Fizik, kimya, biyoloji", 
    "FM": "Frekans modülasyonu",
    "IÜ": "Işık Üniversitesi",
    "Fr.": "Fransızca", 
    "FSMVÜ": "Fatih Sultan Mehmet Vakıf Üniversitesi", 
    "FÜ": "Fırat Üniversitesi",
    "g": "Gram", 
    "GAMHK": "Güney Avrupa Müttefik Hava Kuvvetleri",
    "GAP": "Güneydoğu Anadolu Projesi", 
    "GAPBKİ": "GAP Bölge Kalkınma İdaresi Başkanlığı", 
    "GATA": "Gülhane Askerî Tıp Akademisi", 
    "GAUT": "Güneydoğu Asya Uluslar Topluluğu",
    "GAZÜ": "Gaziantep Üniversitesi",
    "GB": "Gigabyte",
    "GBT": "Genel Bilgi Taraması", 
    "GDAOP": "Güney ve Doğu Afrika Ortak Pazarı",
    "Gen.": "General",
    "geom.": "Geometri", 
    "GİB": "Gelir İdaresi Başkanlığı", 
    "GİGM": "Başbakanlık Güvenlik İşleri Genel Müdürlüğü", 
    "gn.": "Genel",
    "Gnkur.": "Genelkurmay",
    "GOÜ": "Gaziosmanpaşa Üniversitesi", 
    "Gön.": "Gönderen", 
    "gr.": "Gramer", 
    "Grt": "Groston", 
    "GSGM": "Gençlik ve Spor Genel Müdürlüğü", 
    "GSM": "Mobil cep telefonu", 
    "GSMH": "Gayrisafi millî hasıla", 
    "GSÜ": "Galatasaray Üniversitesi", 
    "GSYH": "Gayrisafi yurt içi hasıla", 
    "GTÖ": "Gıda ve Tarım Örgütü",
    "GÜ": "Gazi Üniversitesi", 
    "GYD": "Görüntülü yoğun disk", 
    "GYTE": "Gebze Yüksek Teknoloji Enstitüsü", 
    "GZK": "Gazikent Üniversitesi",
    "HA": "Harp Akademisi",
    "HABITAT": "Birleşmiş Milletler İnsan Yerleşimleri Konferansı", 
    "HACCP": "Kritik kontrol noktalarında tehlike analizi", 
    "HAVAŞ": "Hava Alanları ve Yer Hizmetleri Genel Müdürlüğü", 
    "hay. b.": "Hayvan bilimi", 
    "haz.": "Hazırlayan", 
    "HDD": "Ana bellek sürücüsü",   
    "hek.": "Hekimlik", 
    "HGK": "Harita Genel Komutanlığı", 
    "HGM": "Haberleşme Genel Müdürlüğü", 
    "HİTÜ": "Hitit Üniversitesi", 
    "HKK": "Hava Kuvvetleri Komutanlığı", 
    "hl": "Hektolitre", 
    "hlk.": "Halk ağzı", 
    "HM": "Hazine Müsteşarlığı", 
    "hm": "Hektometre", 
    "HMUK": "Hukuk Muhakemeleri Usulü Kanunu", 
    "HO": "Harp Okulu",
    "HRÜ": "Harran Üniversitesi",
    "Hs. Uzm.": "Hesap Uzmanı", 
    "HSSGM": "Sağlık Bakanlığı Hudut ve Sahiller Sağlık Genel Müdürlüğü", 
    "HUK": "Maliye Bakanlığı Hesap Uzmanları Kurulu Başkanlığı", 
    "huk.": "Hukuk", 
    "HÜ": "Hacettepe Üniversitesi", 
    "Hv. Kuv. K.": "Hava Kuvvetleri Komutanı", 
    "Hv. Kuv.": "Hava Kuvvetleri", 
    "Hz. öz.": "Hizmete özel", 
    "Hz.": "Hazreti",  
    "IĞDÜ": "Iğdır Üniversitesi", 
    "İAÜ": "İstanbul Aydın Üniversitesi", 
    "İbr.": "İbranice", 
    "İBÜ": "İstanbul Bilim Üniversitesi", 
    "İBÜN": "İstanbul Bilgi Üniversitesi", 
    "İDBÜ": "İhsan Doğramacı Bilkent Üniversitesi",
    "İDT": "İktisadi Devlet Teşekkülleri", 
    "İEGM": "İlaç ve Eczacılık Genel Müdürlüğü", 
    "İETT": "İstanbul Elektrik, Tünel, Tramvay İşletmesi", 
    "İEÜ": "İzmir Ekonomi Üniversitesi",
    "İGB": "Başbakanlık İdareyi Geliştirme Başkanlığı", 
    "İGEME": "İhracatı Geliştirme Etüd Merkezi", 
    "İGM": "İlköğretim Genel Müdürlüğü", 
    "İHB": "İnsan Hakları Başkanlığı", 
    "İKB": "İslam Kalkınma Bankası", 
    "İKBÜ": "İstanbul Kemerburgaz Üniversitesi", 
    "İKÖ": "İslam Konferansı Örgütü",  
    "İKÜ": "İstanbul Kültür Üniversitesi", 
    "İKV": "İktisadi Kalkınma Vakfı", 
    "İLBANK": "İller Bankası Genel Müdürlüğü", 
    "İMKB": "İstanbul Menkul Kıymetler Borsası", 
    "İng.": "İngilizce", 
    "INTERPOL": "Uluslararası Cinayet Polisi Komisyonu",  
    "İO": "İlköğretim okulu",
    "is.": "İsim",
    "ISBN": "Uluslararası standart kitap numarası",  
    "İSDEMİR": "İskenderun Demir Çelik Fabrikaları", 
    "İSEDAK": "İslam Konferansı Örgütü Ekonomik ve Ticari İş Birliği Daimî Komitesi", 
    "İSG": "İş Sağlığı ve Güvenliği Genel Müdürlüğü", 
    "İSKİ": "İstanbul Su ve Kanalizasyon İdaresi", 
    "İSKYF": "İktisadi ve Sosyal Kalkınma Yatırım Fonları",  
    "ISMN": "Uluslararası standart müzik numarası", 
    "İSO": "İstanbul Sanayi Odası", 
    "İsp.": "İspanyolca", 
    "ISSN": "Uluslararası standart dizi numarası", 
    "İŞKUR": "Türkiye İş Kurumu",
    "işl.": "İşleyen", 
    "İŞOT": "İstanbul Şehirler Arası Otobüs Terminali", 
    "İt.": "İtalyanca", 
    "İTB": "İstanbul Ticaret Borsası", 
    "İTG": "İç Ticaret Genel Müdürlüğü", 
    "İTİCÜ": "İstanbul Ticaret Üniversitesi", 
    "ITO": "Birleşmiş Milletler Uluslararası Ticaret Birliği",
    "İTO": "İstanbul Ticaret Odası", 
    "İTÜ": "İstanbul Teknik Üniversitesi", 
    "İÜ": "İstanbul Üniversitesi", 
    "İYTE": "İzmir Yüksek Teknoloji Enstitüsü", 
    "İZTB": "İzmir Ticaret Borsası", 
    "İZTO": "İzmir Ticaret Odası", 
    "Jap.": "Japonca", 
    "jeol.": "Jeoloji", 
    "JGK": "Jandarma Genel Komutanlığı", 
    "JHY": "Japon Hava Yolları", 
    "kal": "Kalori", 
    "KARDEMİR": "Karabük Demir Çelik Fabrikaları", 
    "KASTB": "Kuzey Amerika Serbest Ticaret Bölgesi",
    "KAÜ": "Kafkas Üniversitesi", 
    "KBB": "Kulak, Burun, Boğaz", 
    "KBÜ": "Karabük Üniversitesi", 
    "KDV": "Katma değer vergisi", 
    "KED": "Kablosuz Erişim Düzeneği", 
    "KEGM": "Kıyı Emniyeti Genel Müdürlüğü", 
    "KEİ": "Karadeniz Ekonomik İş Birliği",
    "KEYK": "Karşılıklı Ekonomik Yardım Konseyi",  
    "kg": "Kilogram", 
    "KGB": "Sovyet Gizli Haber Alma Teşkilatı", 
    "KGM": "Adalet Bakanlığı Kanunlar Genel Müdürlüğü", 
    "KHK": "Kanun hükmünde kararname",
    "KHÜ": "Kadir Has Üniversitesi", 
    "KHz": "Kilohertz", 
    "KİBİB": "Kalkınma İçin Bölgesel İş Birliği",  
    "KİK": "Kamu İhale Kurumu",  
    "kim.": "Kimya", 
    "KİT": "Kamu İktisadi Teşekkülü", 
    "KİYÜ": "Kilis 7 Aralık Üniversitesi", 
    "KKB": "Karayip Kalkınma Bankası",  
    "KKGM": "Tarım ve Köyişleri Bakanlığı Koruma ve Kontrol Genel Müdürlüğü", 
    "KKK": "Kara Kuvvetleri Komutanlığı", 
    "KKTC": "Kuzey Kıbrıs Türk Cumhuriyeti",
    "KLÜ": "Kırklareli Üniversitesi", 
    "km": "Kilometre", 
    "KMS": "Kurumlar İçi Merkezî Eleme Sınavı", 
    "KMÜ": "Karamanoğlu Mehmetbey Üniversitesi", 
    "KOBİ": "Küçük ve Orta Boy İşletme", 
    "KOİ": "Kamu Ortaklığı İdaresi",
    "koor.": "Koordinasyon", 
    "Kor.": "Kolordu", 
    "Kora.": "Koramiral", 
    "Korg.": "Korgeneral", 
    "KOSGEB": "Küçük ve Orta Ölçekli İşletmeleri Geliştirme ve Destekleme İdaresi Başkanlığı", 
    "KOÜ": "Kocaeli Üniversitesi", 
    "KPDS": "Kamu Personeli Yabancı Dil Bilgisi Seviye Tespit Sınavı", 
    "KPSS": "Kamu Personel Seçme Sınavı", 
    "kr.": "Kuruş",
    "krş.": "Karşılaştırınız", 
    "KSDB": "Kanserle Savaş Dairesi Başkanlığı", 
    "KSGM": "Kadının Statüsü Genel Müdürlüğü", 
    "KSÜ": "Kahramanmaraş Sütçü İmam Üniversitesi", 
    "KTKB": "Karadeniz Ticaret ve Kalkınma Bankası", 
    "KTO": "Karatay Üniversitesi", 
    "KTOP": "Karayip Topluluğu ve Ortak Pazarı", 
    "KTÖGM": "Kız Teknik Öğretim Genel Müdürlüğü",
    "KTÜ": "Karadeniz Teknik Üniversitesi", 
    "KUGM": "Kara Ulaştırma Genel Müdürlüğü",
    "Kur. Bşk.":  "Kurmay Başkanı", 
    "Kur.": "Kurmay", 
    "KÜ": "Kastamonu Üniversitesi",
    "KVMGM": "Kültür Varlıkları ve Müzeler Genel Müdürlüğü", 
    "KYGM": "Kütüphaneler ve Yayımlar Genel Müdürlüğü", 
    "l": "Litre",
    "LABB": "Latin Amerika Bütünleşme Birliği",  
    "LAKEK": "Latin Amerika ve Karayipler Ekonomik Komisyonu", 
    "LASTB": "Latin Amerika Serbest Ticaret Bölgesi",  
    "Lat.": "Latince", 
    "LCV": "Lütfen cevap veriniz", 
    "LES": "Lisansüstü Eğitim Giriş Sınavı", 
    "LP": "Uzunçalar",   
    "LPG": "Sıvılaştırılmış Petrol Gazı",  
    "Ltd.": "Limitet", 
    "LYS": "Lisans Yerleştirme Sınavı", 
    "m": "Metre", 
    "M": "Miladi", 
    "Mac.": "Macarca", 
    "Mah.": "Mahalle", 
    "MAKÜ": "Mehmet Akif Ersoy Üniversitesi", 
    "man.": "Mantık", 
    "MAÖ": "Merkezî Antlaşma Örgütü", 
    "MASAK": "Mali Suçları Araştırma Kurulu Başkanlığı", 
    "mat.": "Matematik", 
    "MAÜ": "Mardin Artuklu Üniversitesi", 
    "MB": "Megabyte",  
    "Md.": "Müdür", 
    "MEB": "Millî Eğitim Bakanlığı",  
    "mec.": "Mecaz", 
    "MEÜ": "Mersin Üniversitesi", 
    "MGK": "Millî Güvenlik Kurulu Genel Sekreterliği", 
    "MGM": "İçişleri Bakanlığı Mahalli İdareler Genel Müdürlüğü", 
    "MĞÜ": "Muğla Üniversitesi",
    "MHAT": "Merkezî Haber Alma Teşkilatı",  
    "MHz": "Megahertz", 
    "MİGEM": "Maden İşleri Genel Müdürlüğü", 
    "MİLE": "Millî Emlak Genel Müdürlüğü",
    "mim.": "Mimarlık", 
    "min.": "Mineraloji", 
    "MİT": "Millî İstihbarat Teşkilatı Müsteşarlığı", 
    "MK": "Medeni Kanun",  
    "MKB": "Millî Kütüphane Başkanlığı", 
    "MKE": "Makine ve Kimya Endüstrisi Kurumu",  
    "MKS": "Metre-Kilogram-Saat", 
    "MKÜ": "Mustafa Kemal Üniversitesi", 
    "MKYK": "Merkez Karar Yönetim Kurulu",
    "mm": "Milimetre", 
    "MOBESE": "Bölgesel güvenlik sistemi", 
    "MOSSAD": "İsrail Gizli Haber Alma Örgütü", 
    "MÖ": "Milattan önce", 
    "MPİ": "Millî Piyango İdaresi Genel Müdürlüğü", 
    "MPM": "Millî Prodüktivite Merkezi", 
    "MR": "Manyetik rezonans görüntüleme", 
    "MS": "Milattan sonra", 
    "MSB": "Millî Savunma Bakanlığı", 
    "MSGSÜ": "Mimar Sinan Güzel Sanatlar Üniversitesi", 
    "MTA": "Maden Tetkik ve Arama Genel Müdürlüğü", 
    "MÜ": "Marmara Üniversitesi", 
    "Müh.": "Mühendis", 
    "Mür.": "Müracaat", 
    "müz.": "Müzik", 
    "MYK": "Mesleki Yeterlilik Kurumu", 
    "NASA": "Amerikan Ulusal Havacılık ve Uzay Araştırmaları Merkezi",  
    "NATO": "Kuzey Atlantik Antlaşması Teşkilatı", 
    "NEÜ": "Nevşehir Üniversitesi", 
    "NĞÜ": "Niğde Üniversitesi", 
    "NKÜ": "Namık Kemal Üniversitesi", 
    "No.": "Numara", 
    "NOTAM": "Havacılar ve denizciler için uyarı bildirimi", 
    "Nö.": "Nöbetçi", 
    "Nö. Sb.": "Nöbetçi subayı", 
    "NVİGM": "Nüfus ve Vatandaşlık İşleri Genel Müdürlüğü", 
    "OAİB": "Orta Anadolu İhracatçı Birlikleri Genel Sekreterliği",
    "OAOP": "Orta Amerika Ortak Pazarı",  
    "ODTÜ": "Orta Doğu Teknik Üniversitesi",
    "ODÜ": "Ordu Üniversitesi",
    "OGM": "Orman Genel Müdürlüğü", 
    "OKÖNEGM": "Okul Öncesi Eğitimi Genel Müdürlüğü", 
    "Okt.": "Okutman", 
    "OKÜ": "Osmaniye Korkut Ata Üniversitesi", 
    "OMÜ": "Ondokuz Mayıs Üniversitesi",
    "Onb.": "Onbaşı", 
    "Opr.": "Operatör", 
    "Or.": "Ordu", 
    "Ora.": "Oramiral", 
    "Ord.": "Ordinaryüs", 
    "Org.": "Orgeneral",
    "ORKÖY": "Orman-Köy İlişkileri Genel Müdürlüğü", 
    "Ort.": "Ortaklık", 
    "OSB": "Organize Sanayi Bölgesi", 
    "Osm. T.": "Osmanlı Türkçesi", 
    "OYAK": "Ordu Yardımlaşma Kurumu", 
    "OYEGM": "Öğretmen Yetiştirme ve Eğitimi Genel Müdürlüğü", 
    "ÖÇKKB": "Özel Çevre Koruma Kurumu Başkanlığı", 
    "ÖİB": "Özelleştirme İdaresi Başkanlığı", 
    "öl.": "Ölüm tarihi", 
    "ÖÖKGM": "Özel Öğretim Kurumları Genel Müdürlüğü", 
    "ör.": "Örnek", 
    "ÖRGM": "Özel Eğitim Rehberlik ve Danışma Hizmetleri Genel Müdürlüğü", 
    "ÖSGM": "Sanayi ve Ticaret Bakanlığı Ölçüler ve Standartlar Genel Müdürlüğü", 
    "ÖSS": "Öğrenci Seçme Sınavı", 
    "ÖSYM": "Ölçme, Seçme ve Yerleştirme Merkezi", 
    "ÖTV": "Özel tüketim vergisi", 
    "ÖYK": "Özelleştirme Yüksek Kurulu", 
    "ÖYS": "Öğrenci Yerleştirme Sınavı",
    "öz.": "Özel", 
    "ÖZİ": "Özürlüler İdaresi Başkanlığı",
    "ÖZÜ": "Özyeğin Üniversitesi", 
    "PAÜ": "Pamukkale Üniversitesi", 
    "ped.": "Pedagoji", 
    "PETKİM": "Petrokimya Endüstrisi Genel Müdürlüğü", 
    "PİEAÜÖ": "Petrol İhraç Eden Arap Ülkeleri Örgütü",  
    "PİEÜT": "Petrol İhraç Eden Ülkeler Teşkilatı",
    "PİGM": "Petrol İşleri Genel Müdürlüğü", 
    "PK": "Posta kutusu", 
    "PO": "Petrol Ofisi", 
    "POAŞ": "Petrol Ofisi Anonim Şirketi", 
    "Port.": "Portekizce", 
    "Prof.": "Profesör", 
    "psikol.": "Psikoloji", 
    "PTT": "Posta ve Telgraf Teşkilatı Genel Müdürlüğü",
    "RAM": "Bilgisayarda okunabilir ve yazılabilir bellek", 
    "RC": "Kızılhaç",
    "RK": "Rekabet Kurumu", 
    "RNA": "Ribo nükleik asit", 
    "ROM": "Bilgisayarda yalnızca okunabilir bellek", 
    "RSHM": "Refik Saydam Hıfzıssıhha Merkezi Başkanlığı",
    "RTÜK": "Radyo ve Televizyon Üst Kurulu", 
    "Rum.": "Rumca", 
    "Rus.": "Rusça", 
    "RÜ": "Rize Üniversitesi",
    "s.": "Sayfa", 
    "sa.": "Saat", 
    "SAS": "Su Altı Savunma", 
    "SAT": "Su Altı Taarruz",
    "SATEM": "Savunma Sanayii ve Teknoloji Eğitim Merkezi", 
    "SAÜ": "Sakarya Üniversitesi", 
    "Sb.": "Subay", 
    "SB": "Sağlık Bakanlığı", 
    "SBF": "Siyasal Bilgiler Fakültesi", 
    "SBS": "Seviye Belirleme Sınavı", 
    "SDÜ": "Süleyman Demirel Üniversitesi", 
    "SEFD Bşk.": "Millî Savunma Bakanlığı Seferberlik Dairesi Başkanlığı", 
    "SEK": "Süt Endüstrisi Kurumu Sanayi ve Ticaret Anonim Şirketi", 
    "SEKA": "Selüloz ve Kâğıt Sanayii Kurumu",
    "sf.": "Sıfat", 
    "SG": "Sahil Güvenlik", 
    "SGK": "Sosyal Güvenlik Kurumu",  
    "SGM": "Sanayi ve Ticaret Bakanlığı Sanayi Genel Müdürlüğü", 
    "SHÇEK": "Sosyal Hizmetler ve Çocuk Esirgeme Kurumu", 
    "SHGM": "Sivil Havacılık Genel Müdürlüğü", 
    "SHÖ": "Sivil Havacılık Örgütü", 
    "SİÜ": "Siirt Üniversitesi", 
    "SKT": "Son kullanma tarihi", 
    "Sl.": "Slavca", 
    "Sn.": "Sayın", 
    "sn.": "Saniye", 
    "snt.": "Santral", 
    "SNÜ": "Sinop Üniversitesi", 
    "Sok.": "Sokak", 
    "SOS": "Uluslararası yardım isteme uyarısı",
    "sos.": "Sosyoloji", 
    "sp.": "Spor", 
    "SPK": "Sermaye Piyasası Kurulu",
    "Srp.": "Sırpça", 
    "SSCB": "Sovyet Sosyalist Cumhuriyetleri Birliği",  
    "SSDB": "Sağlık Bakanlığı Sıtma Savaş Dairesi Başkanlığı", 
    "SSK": "Sosyal Sigortalar Kurumu", 
    "SSM": "Savunma Sanayi Müsteşarlığı", 
    "STB": "Sanayi ve Ticaret Bakanlığı", 
    "STK": "Sivil Toplum Kuruluşu", 
    "STÖ": "Sivil Toplum Örgütü", 
    "SUGES": "Sudan gelen sağlık", 
    "SÜ": "Sabancı Üniversitesi",  
    "SYD": "Sayısal yoğun disk", 
    "SYDGM": "Sosyal Yardımlaşma ve Dayanışma Genel Müdürlüğü", 
    "Şb.": "Şube", 
    "ŞÜ": "Şırnak Üniversitesi",
    "t": "Ton", 
    "T.C.": "Türkiye Cumhuriyeti",
    "TAA": "Türkiye Adalet Akademisi", 
    "TAEK": "Türkiye Atom Enerjisi Kurumu", 
    "TAGEM": "Tarımsal Araştırmalar Genel Müdürlüğü", 
    "tar.": "Tarih", 
    "TARİŞ": "Tarım Satış Kooperatifleri Birliği", 
    "TASS": "Sovyetler Birliği Telgraf Ajansı", 
    "TAŞ": "Türk Anonim Şirketi",
    "TAU": "Teknik Araştırma ve Uygulama Genel Müdürlüğü", 
    "Tb.": "Tabur", 
    "TBB": "Türkiye Bankalar Birliği", 
    "TBMM": "Türkiye Büyük Millet Meclisi", 
    "TCDD": "Türkiye Cumhuriyeti Devlet Demiryolları", 
    "TCK": "Türkiye Cumhuriyeti Karayolları", 
    "TCMB": "Türkiye Cumhuriyet Merkez Bankası", 
    "TCZB": "Türkiye Cumhuriyeti Ziraat Bankası", 
    "TDÇİ": "Türkiye Demir Çelik İşletmeleri", 
    "TDİ": "Türkiye Denizcilik İşletmeleri", 
    "TDK": "Türk Dil Kurumu", 
    "TEAE": "Tarımsal Ekonomi Araştırma Enstitüsü", 
    "TEAŞ": "Türkiye Elektrik Üretim Anonim Şirketi", 
    "TEDAŞ": "Türkiye Elektrik Dağıtım Anonim Şirketi", 
    "TEDGEM": "Teşkilatlanma ve Destekleme Genel Müdürlüğü", 
    "TEFE": "Toptan eşya fiyatları endeksi", 
    "TEİAŞ": "Türkiye Elektrik İletim Anonim Şirketi", 
    "TEK": "Türkiye Elektrik Kurumu", 
    "tek.": "Teknik", 
    "tel.": "Telefon", 
    "telg.": "Telgraf", 
    "TEM": "Avrupa Transit Kara Yolu",   
    "TEMSAN": "Türkiye Elektromekanik Sanayii", 
    "TETAŞ": "Türkiye Elektrik, Ticaret ve Taahhüt Anonim Şirketi",  
    "TFF": "Türkiye Futbol Federasyonu Başkanlığı",
    "TGC": "Türkiye Gazeteciler Cemiyeti", 
    "TGM": "Kültür ve Turizm Bakanlığı Tanıtma Genel Müdürlüğü", 
    "TGS": "Türkiye Gazeteciler Sendikası", 
    "Tğm.": "Teğmen", 
    "THA": "Türk Haberler Ajansı", 
    "THK": "Türk Hava Kurumu", 
    "THS": "Türk Havacılık Sanayii", 
    "THSGM": "Telif Hakları ve Sinema Genel Müdürlüğü", 
    "THY": "Türk Hava Yolları", 
    "TIR": "Uluslararası Kara Yolu Taşımacılığı",
    "tic.": "Ticaret", 
    "TİGEM": "Tarım İşletmeleri Genel Müdürlüğü", 
    "TİKA": "Türk İş Birliği ve Koordinasyon Ajansı Başkanlığı", 
    "TİM": "Türkiye İhracatçılar Merkezi", 
    "TİSK": "Türkiye İşverenler Sendikası Konfederasyonu",
    "tiy.": "Tiyatro", 
    "TKAE": "Türk Kültürünü Araştırma Enstitüsü", 
    "TKB": "Türkiye Kalkınma Bankası", 
    "TKF": "Toplu Konut Fonu", 
    "TKGM": "Tapu ve Kadastro Genel Müdürlüğü", 
    "TKİ": "Türkiye Kömür İşletmeleri", 
    "TL": "Türk lirası",
    "tlks.": "Teleks", 
    "tls.": "Telsiz", 
    "TM": "Türk malı", 
    "TMMOB": "Türk Mühendis ve Mimar Odaları Birliği", 
    "TMO": "Toprak Mahsulleri Ofisi", 
    "TMSF": "Tasarruf Mevduatı Sigorta Fonu",  
    "TMSK": "Türkiye Muhasebe Standartları Kurulu", 
    "TNCÜ": "Tunceli Üniversitesi", 
    "TOBB": "Türkiye Odalar ve Borsalar Birliği", 
    "TOBB ETÜ": "TOBB Ekonomi ve Teknoloji Üniversitesi", 
    "TODAİE": "Türkiye ve Orta Doğu Amme İdaresi Enstitüsü", 
    "TOEFL": "Yabancı dil olarak İngilizce testi", 
    "TOKİ": "Toplu Konut İdaresi Başkanlığı", 
    "Top.": "Topçu", 
    "TÖMER": "Türkçe Öğretim Merkezi", 
    "TP": "Türk Petrolleri", 
    "TPAO": "Türkiye Petrolleri Anonim Ortaklığı", 
    "TPE": "Türk Patent Enstitüsü", 
    "TR": "Türkiye", 
    "TRGM": "Tarım Reformu Genel Müdürlüğü",
    "TRKGM": "Tüketicinin ve Rekabetin Korunması Genel Müdürlüğü", 
    "TRS": "Toros Üniversitesi", 
    "TRT": "Türkiye Radyo ve Televizyon Kurumu",
    "TSE": "Türk Standartları Enstitüsü", 
    "TSİ": "Türkiye saati ile", 
    "TSK": "Türk Silahlı Kuvvetleri",
    "TSKB": "Türkiye Sınai Kalkınma Bankası", 
    "TT": "Türkiye Türkçesi", 
    "TTB": "Türk Tabipleri Birliği", 
    "TTK": "Türk Tarih Kurumu", 
    "TTKB": "Talim ve Terbiye Kurulu Başkanlığı", 
    "TTOK": "Türkiye Turing ve Otomobil Kurumu", 
    "TUBİM": "Türkiye Uyuşturucu ve Uyuşturucu Bağımlılığını İzleme Merkezi", 
    "Tug.": "Tugay", 
    "Tuğa.": "Tuğamiral", 
    "Tuğg.": "Tuğgeneral",
    "PDR": "Psikolojik danışmanlık ve rehberlik",
}